nome = input("Digite seu nome: ")
idade = int(input("Digite sua idade: "))
altura = float(input("Digite sua altura: "))
peso = float(input("Digite seu peso: "))

print("-" * 30)
print("OS dados coletados foram:")
print("Seu nome: ",nome)
print("Sua idade: ",idade," anos")
print("Sua altura: ",altura, " mts")
print("Seu peso ", peso," kgs")